version: '3.9'

services:
  web:
    networks:
      - app_network  # Connect the web service to the app_network
    build: ./web  # Build the Docker image for the web service from the Dockerfile in the ./web directory
    command: python server.py  # Run this command when the container starts
    volumes:
      - ./web:/app  # Mount the ./web directory on the host to the /app directory in the container
    ports:
      - "8080:8080"  # Map port 8080 in the container to port 8080 on the host
    environment:  # Set these environment variables inside the container
      - DEBUG=True
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=example
      - POSTGRES_PASSWORD=example
      - POSTGRES_DATABASE=sreality
      - ALLOWED_HOSTS=*
    depends_on:  # Start the db service before starting this one
      - db

  db:
    networks:
      - app_network  # Connect the db service to the app_network
    container_name: db  # Name the container "db"
    image: 'postgres:13'  # Use the postgres:13 Docker image
    environment:  # Set these environment variables inside the container
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
      POSTGRES_DB: sreality
    volumes:  # Mount these volumes inside the container
      - pgdata:/var/lib/postgresql/data
      - ./web/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: -c 'shared_preload_libraries=pg_stat_statements' -c 'pg_stat_statements.track=all'

  scrapy:
    networks:
      - app_network  # Connect the scrapy service to the app_network
    build:  # Build the Docker image for the scrapy service
      context: .
      dockerfile: new_scrapyproject/Dockerfile
    command: >  # Run this command when the container starts
      scrapy crawl sreality
      -a project_path=/app/new_scrapyproject
    depends_on:  # Start the db service before starting this one
      - db
    environment:  # Set these environment variables inside the container
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=sreality
      - POSTGRES_USER=example
      - POSTGRES_PASSWORD=example


volumes:
  pgdata:

networks:
  default:
    name: luxonis_default

  app_network:
    name: luxonis_app_network
