version: '3.9'

services:
  web:
    networks:
      - app_network
    build: ./web
    command: python server.py
    volumes:
      - ./web:/app
    ports:
      - "8080:8080"
    environment:
      - DEBUG=True
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=example
      - POSTGRES_PASSWORD=example
      - POSTGRES_DATABASE=sreality
      - ALLOWED_HOSTS=*
    depends_on:
      - db

  db:
    networks:
      - app_network
    container_name: db
    image: 'postgres:13'
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
      POSTGRES_DB: sreality
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./web/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: -c 'shared_preload_libraries=pg_stat_statements' -c 'pg_stat_statements.track=all'

  scrapy:
    networks:
      - app_network
    build:
      context: .
      dockerfile: new_scrapyproject/Dockerfile
    command: >
      scrapy crawl sreality
      -a project_path=/app/new_scrapyproject
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=sreality
      - POSTGRES_USER=example
      - POSTGRES_PASSWORD=example


volumes:
  pgdata:

networks:
  default:
    name: luxonis_default

  app_network:
    name: luxonis_app_network
